[package]
name = "resound"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["audio"]

[dependencies]
audio = {path = "audio"}
tokio = { version = "1.45.1", features = ["full"] }
libc = "0.2"
