[package]
name = "audio"
version = "0.1.0"
edition = "2024"

[features]
cargo-clippy = []

[dependencies]
coreaudio-sys = { version = "0.2", default-features = false, features = ["core_audio"] }
objc = "0.2"
